services:
  postgres:
    image: postgres:18.0-alpine
    container_name: frame24-postgres
    environment:
      POSTGRES_USER: frame24
      POSTGRES_PASSWORD: frame24pass
      POSTGRES_DB: frame24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frame24-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frame24"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: frame24-mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    networks:
      - frame24-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: frame24-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: frame24
      RABBITMQ_DEFAULT_PASS: frame24pass
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - frame24-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: frame24-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: frame24
      MINIO_ROOT_PASSWORD: frame24pass
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Painel web
    volumes:
      - minio_data:/data
    networks:
      - frame24-network


  elasticsearch:
    image: elasticsearch:9.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - frame24-network
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:9200' ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: kibana:9.2.0
    container_name: frame24-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - frame24-network
    depends_on:
      elasticsearch:
        condition: service_healthy


volumes:
  es_data:
  postgres_data:
  rabbitmq_data:
  minio_data:

networks:
  frame24-network:
    driver: bridge
